export const GLOBAL_CONFIG = [
  { id: 'Argenis José Acosta Veliz', label: 'ARGENIS ACOSTA', type: 'simple' },
  { id: 'CG SERVICIOS', label: 'CG SERVICIOS', type: 'simple' },
  { id: 'Dainee Yanibeth Zambrano Torres', label: 'DAINEE ZAMBRANO', type: 'simple' },
  { id: 'GRUPO ARLO SYSTEM', label: 'GRUPO ARLO', type: 'simple' },
  { id: 'INVERSIONES PENALVA 2022', label: 'INVERSIONES PEÑALVA', type: 'simple' },
  { id: 'IVENETI', label: 'IVENETI', type: 'split' },
  { id: 'Jeryco Salvador Ortega Palacios', label: 'JERYCO ORTEGA', type: 'simple' },
  { id: 'Jonayker Daniel Mendoza Pérez', label: 'JONAYKER MENDOZA', type: 'simple' },
  { id: 'TELECOMUNICACIONES K. SUAREZ', label: 'K. SUAREZ', type: 'simple' },
  { id: 'Karlanis Tariffa del Chiaro', label: 'KARLANIS TARIFFA', type: 'simple' },
  { id: 'Kenny Marcial Rodríguez García', label: 'KENNY RODRIGUEZ', type: 'split' },
  { id: 'LATIN TELECOM', label: 'LATIN TELECOM', type: 'simple' },
  { id: 'LFM Consultor', label: 'LFM CONSULTOR', type: 'simple' },
  { id: 'Marcial Venancio Rodríguez González', label: 'MARCIAL RODRIGUEZ', type: 'simple' },
  { id: 'Martin Bou Mansour Bakhos', label: 'MARTIN BOU', type: 'split' },
  { id: 'Moisés Enmanuel Urbina Villarreal', label: 'MOISES URBINA', type: 'simple' },
  { id: 'Óscar Eduardo Henriquez Zambrano', label: 'OSCAR HENRIQUEZ', type: 'simple' },
  { id: 'SPECIAL_PE', label: 'PE', type: 'custom' }, 
  { id: 'SMARTLIFE', label: 'SMARTLIFE', type: 'split' },
  { id: 'Jorge Luis Rodríguez Parra', label: 'TERASERVICES VALENCIA', type: 'split' },
  { id: 'Socrates Antonio Sequera Sanchez', label: 'TERASERVICES PUERTO', type: 'split' },
  { id: 'TRS 2048', label: 'TERASERVICES ARAGUA', type: 'simple' }
];

export const DEFAULT_SUMMARY = () => ({
  'Carlos Gabriel Alquedan Pineda': 0,
  'INVERSIONES PENALVA 2022': 0,
  'TELECOMUNICACIONES K. SUAREZ': 0,
  'Marcial Venancio Rodríguez González': 0,
  'LATIN TELECOM': 0,
  'CG SERVICIOS': 0,
  'Moisés Enmanuel Urbina Villarreal': 0,
  'Argenis José Acosta Veliz': 0,
  'Jonayker Daniel Mendoza Pérez': 0,
  'Óscar Eduardo Henriquez Zambrano': 0,
  'Jeryco Salvador Ortega Palacios': 0,
  'SAT SERVICES': 0,
  'LFM Consultor': 0,
  'Ruben Dario Sanchez Avila': 0,
  'Dainee Yanibeth Zambrano Torres': 0,
  'GRUPO ARLO SYSTEM': 0,
  'TRS 2048': 0,
  'A&M SERVICE': 0,
  'Karlanis Tariffa del Chiaro': 0,
  'Kenny Marcial Rodríguez García': { ftth: 0, rf: 0 },
  SMARTLIFE: { ftth: 0, rf: 0 },
  'Martin Bou Mansour Bakhos': { ftth: 0, rf: 0 },
  IVENETI: { ftth: 0, rf: 0 },
  'Jorge Luis Rodríguez Parra': { ftth: 0, rf: 0 },
  'Socrates Antonio Sequera Sanchez': { ftth: 0, rf: 0 },
});